-- https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Exponential_identity
require "math"

local function exp_sqrt(x: number): number
  if ((x == 0) or (x == 1) or (x == math.huge)) then
    return x
  elseif (x < 0) then
    return (0 / 0)
  end
  
  return math.exp(0.5 * math.log(x))
end

local function main(): cint
  local x, y = exp_sqrt(2), math.sqrt(2)
  
  print(x, y)
  
  return 0
end

return main()
