-- https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Exponential_identity
require "math"

local function log_nroot(x: number, n: number): number
  if ((x == math.huge) or (x == -math.huge) or
      (n == math.huge) or (n == -math.huge)) then
    return (0 / 0)
  end
  
  return math.pow(2, (1 / n) * math.log2(x))
end

local function main(): cint
  local x: number = log_nroot(2.0, 4)
  local y: number = math.pow(2.0, 0.25)
  
  print(x, y)

  return 0
end

return main()
